### ISSUE TITLE
/altinitycloud/quickstartguide/ cannot be shared on Linkedin and Facebook

### ISSUE THREAD

**Issue by besteffects** [Altinity/documentationIssues#10]
Sharing with LInkedin and Facebook  returns errors

For example, Linkedin opens the link https://www.linkedin.com/shareArticle/?mini=true&url=/altinitycloud/quickstartguide/&title=Quick%20Start%20Guide
and Facebook:
https://www.facebook.com/sharer/sharer.php?u=%2Faltinitycloud%2Fquickstartguide%2F

**Comment by johnhummelAltinity** [comment]
I'll look into it - looks like it isn't giving the full URL for some reason....

**Comment by johnhummelAltinity** [comment]
Tested out and should be fixed. I'll double check on other browsers but we should be happy now.
