### ISSUE TITLE
Install Guide

### ISSUE THREAD

**Issue by filimonov** [Altinity/documentationIssues#3]
> ```
> version=20.8.7.15
> sudo yum install -y clickhouse-server=$version clickhouse-client=$version
> ```

That is wrong.

Correct version

```
version=20.8.7.15
sudo yum install clickhouse-server-${version} clickhouse-client-${version}
``` 

(dash instead of equal sign)

**Comment by johnhummelAltinity** [comment]
Got it - it's been fixed.  Sorry for the delay - I didn't see the notifications on these.
