### ISSUE TITLE
21.1 Releases

### ISSUE THREAD

**Issue by vladimir-golovchenko** [Altinity/documentationIssues#6]
I think the title of [ClickHouse Altinity Stable Release™ 21.1](https://docs.altinity.com/altinitystablerelease/releasenotes/releases/21.1/) should depict the *full* version like _ClickHouse Altinity Stable Release™ **21.1.7.1**_.

**Comment by johnhummelAltinity** [comment]
Good point - I'll make that update.

**Comment by johnhummelAltinity** [comment]
OK - change made!  Let me know if you feel we need any other tweaks.

https://docs.altinity.com/altinitystablerelease/releasenotes/releases/21.1/
