### ISSUE TITLE
/clickhouseonkubernetes/kubernetesquickstartguide/quickpersistentstorage/

### ISSUE THREAD

**Issue by Slach** [Altinity/documentationIssues#9]
according to https://github.com/Altinity/clickhouse-operator/issues/716
please remove
```
storageClassName: default
```
or replace to
```
storageClassName: standard
```

**Comment by johnhummelAltinity** [comment]
Good catch - I'll make the change now.

**Comment by johnhummelAltinity** [comment]
Update has been made and pushed with a new branch - should be publicly available shortly.
